version: "3.1"
services:
  backend:
    # Configuration for building the docker image for the service
    image: 427510603539.dkr.ecr.ap-south-1.amazonaws.com/backend-api:master
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    container_name: backend
    depends_on: 
      - postgres
    env_file:
      - ./.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Redis Service   
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    restart: always
    container_name: database
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend
  # frontend service
  frontend:
    image: "427510603539.dkr.ecr.ap-south-1.amazonaws.com/frontend-app:master"
    ports:
      - "3000:3000"
    restart: always
    container_name: frontend
    env_file:
        - ./.env
    environment:
      REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    networks:
      - backend

networks:
  backend: 
